name: Generate API
permissions: write-all
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Start API wrapper workflow
        run: |
          curl -X POST \
          -d '{ "event_type": "tag_created", "client_payload": { "tag": "v1.0.0"}}' \
          -H "Content-Type: application/json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/mismirnov/celenium-api-go/dispatches
